### ISSUE TITLE
Manually inputting values not working 

### ISSUE THREAD

**Issue by walegbenga** [cliveharber/gettingMean-2#12]
I tried to pass the comment._id in an hidden form manually to be used for adding likes to a comment but it's not working. This is what I have done so far

```
<div *ngFor="let comment of post.comments | mostRecentFirst" class="row review">
          <div class="col-12 no-gutters review-header">
            <div class="col-12">
              <p [innerHTML]="comment.commentContent | htmlLineBreaks"></p>
              <p [innerHTML]="comment.voteUp"> likes</p>
              <p [innerHTML]="comment.voteDown"></p>
            </div>
            <form (ngSubmit)="onCommentVoteUpSubmit()">
              <hr>
                <div class="col-12">
                  <input type="input" hidden="true" class="form-control" id="id" name="id" [(ngModel)]="newComment._id" value="{{ comment._id }}">
                  <button type="submit" class="btn btn-primary float-right" style="margin-left:15px">Vote up</button>
                </div>
            </form>
            <small class="reviewTimestamp">{{ comment.createdOn | date : 'd MMMM yyyy'}}</small>
          </div>
        </div>
```

When I  to console.log it, it returns  `Undefined`

This is what I have in 
> post-details.component.ts 

```
public onCommentVoteUpSubmit(): void {
    console.log(id);
    this.nodeCommDataService
      .addVoteUpComment(this.post._id, this.newComment)
      .then((comment: Comment) => {
        let comments = this.post.comments.slice(0);
        comments.unshift(comment);
        this.post.comments = comments;
      });
  }
```
and this is `newComment`
```
public newComment: Comment = {
    _id: '',
    user: '',
    commentContent: '',
    voteDown: 0,
    voteUp: 0
  };
```
What am I missing?

**Comment by cliveharber** [comment]
From brief purely code read I can only identify the following:

The "hidden" field isn't actually hidden. In HTML hidden form fields have a type="hidden" rather than what you've put.
The "id" that you're logging out in onCommentVoteUpSubmit() doesn't exist in the given context, so will be undefined. What I think you wanted to log was this.newComment._id.

I hope this helps

**Comment by walegbenga** [comment]
What you said was what I did from the onset. i.e. `this.newComment._id` but it keeps returning error when compiled. It always complain that `_id` is not set in Comment class while it is set.

The problem is that am unable access any of the Comment field in the method

That is why I thought of doing it another way

P.s. am now able to get rid of the error, but still unable to pass the id from the form to the `onCommentVoteUpSubmit()`

**Comment by cliveharber** [comment]
The first question that comes to mind then is: why are you trying to set this data at the template level. If the comment id is already in the component, why not set it at at component level? So at the point where you need it.

The form isn’t posting directly back to the server as you’re using ngModel. I assume that the comment data is already fully populated, so has already been submitted to the database in order to get the _id from MongoDB. If this is actually a brand new comment (which I suspect) and not a concept leak (which I also suspect), then newComment shouldn’t have an _id unless you’ve given it one - I think that you’re trying to do this, although I suspect that sending data with an already assigned _id field will cause the original comment to be overwritten - maybe this is what you’re shooting for, maybe it isn’t.

So further questions as they’re not obvious from the code that you’ve pushed up:

Are you trying to add voting to comments that are already submitted and display in the page as a list? In which case, why are you using a newComment class to hold that data? newComment shouldn’t have an _id field, it should only know of its content and maybe which post it is being attached to. You might need a different concept/class to hold the comments that you want to provide voting functionality for.
Are you trying to add voting to newComment? In which case, does this make sense and also _id won’t be defined as newComment is exactly that, a new comment, and therefore hasn’t been submitted to the database yet.

My feeling is that you’re mixing concepts in your page. A comment and a newComment might use the same class (Comment), but the comment is there to hold data for comments in the comments list and newComment is there for holding form data. The only thing a newComment should know about the voting system is that the upVote and downVote data is 0. It's the comments that care about voting and if you’re providing functionality like this, then maybe it's time to break the listing out into a list of components where each Comment component manages its own voting data.

Clive Harber
CTO // DistortedThinking
e: clive@distortedthinking.co.uk
w: www.distortedthinking.agency
t: +44 7815 166434

**Comment by walegbenga** [comment]
**_why are you trying to set this data at the template level_**

From the onset, I thought the comment id is available in the component level but when I use `this.comment._id`, it returns
> Undefined

I thought, it I could get it that way. I tried `this.post.comments._id`, it also returned
> Undefined

That is why I chose the part of template component.

**_If this is actually a brand new comment (which I suspect)_**

This is not a brand new comment. USER A makes a comment, USER B, after reading the comment, click on the LIKE button to like the comment.

**_I suspect that sending data with an already assigned _id field will cause the original comment to be overwritten - maybe this is what you’re shooting for, maybe it isn’t._**

No, that is not am aiming for.

**_Are you trying to add voting to comments that are already submitted and display in the page as a list?_**

Yes, that is my goal.

**_In which case, why are you using a newComment class to hold that data?_**

Reason why I did that is not far fetched, I simply wanted to use the `newComment` for creating (1) a new comment (2) updating an existing comment (3) using it in voting system.

This is what am trying to achieve.

Am sorry for incessant messages. That is due to a newbie trying to get to the professional level

**Comment by cliveharber** [comment]
As what you’re doing isn’t related to issues with the book text which is what this repo/issues list is for and beyond the scope given in that book, message me directly at clive@distortedthinking.co.uk <mailto:clive@distortedthinking.co.uk> and I will see what I can do to help you. 

Cheers

Clive Harber
CTO // DistortedThinking
e: clive@distortedthinking.co.uk
w: www.distortedthinking.agency
t: +44 7815 166434

**Comment by walegbenga** [comment]
I have message you.

Thanks so much

**Comment by cliveharber** [comment]
I've replied. I'm going to close this now.
